[project]
name = "graphnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "dearpygui>=2.1.0",
    "numpy<2.2.0",
    "pillow>=12.0.0",
    "pydot>=4.0.1",
    "tensorflow>=2.19.0"
]
